# Configuração do Tema Scovl - Funcionalidades Avançadas

[params]
  # Informações do site
  title = "Meu Blog"
  description = "Blog sobre tecnologia, programação e desenvolvimento"
  author = "Seu Nome"
  image = "/images/og-image.jpg"
  
  # Links sociais
  github = "https://github.com/seu-usuario"
  linkedin = "https://linkedin.com/in/seu-usuario"
  email = "seu-email@exemplo.com"
  mastodon = "https://mastodon.social/@seu-usuario"
  rss = "/index.xml"
  
  # Configuração do Giscus (GitHub Discussions)
  [params.giscus]
    repo = "seu-usuario/seu-repo"
    repoId = "R_kgDOGxxxxxxxx"
    category = "Announcements"
    categoryId = "DIC_kwDOGxxxxxxxx"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
    lang = "pt"
  
  # Configuração do Mermaid
  [params.mermaid]
    theme = "default"
    align = "center"
  
  # Configuração de SEO
  [params.seo]
    googleAnalytics = "G-XXXXXXXXXX"
    googleTagManager = "GTM-XXXXXXX"
    facebookPixel = "XXXXXXXXXX"
  
  # Configuração de performance
  [params.performance]
    lazyLoading = true
    preloadCritical = true
    minifyCSS = true
    minifyJS = true

# Configuração de taxonomias
[taxonomies]
  tag = "tags"
  category = "categories"

# Configuração de menus
[[menu.main]]
  name = "Início"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 2

[[menu.main]]
  name = "Sobre"
  url = "/page/about/"
  weight = 3

[[menu.main]]
  name = "Contato"
  url = "/page/contact/"
  weight = 4

# Configuração de RSS
[outputFormats]
  [outputFormats.rss]
    mediaType = "application/rss+xml"
    baseName = "index"
    isPlainText = false
    notAlternative = true

# Configuração de sitemap
[outputFormats.sitemap]
  mediaType = "application/xml"
  baseName = "sitemap"
  isPlainText = false
  notAlternative = true

# Configuração de páginas
[outputs]
  home = ["HTML", "RSS", "Sitemap"]
  section = ["HTML", "RSS", "Sitemap"]
  taxonomy = ["HTML", "RSS", "Sitemap"]
  term = ["HTML", "RSS", "Sitemap"]
  page = ["HTML"] 