name = "scovl"
license = "MIT"
licenselink = "https://github.com/scovl/scovl.github.io/blob/master/LICENSE"
description = "A simple and clean theme for Hugo"
homepage = "https://github.com/scovl/scovl.github.io"
tags = ["blog", "minimal", "responsive", "simple", "clean"]
features = ["responsive", "blog", "syntax highlighting"]
min_version = "0.41.0"

[author]
  name = "Vitor Lobo"
  homepage = "https://scovl.github.io"

[original]
  name = "scovl"
  homepage = "https://scovl.github.io"
  repo = "https://github.com/scovl/scovl.github.io" 